spring:
  application:
    name: dubbo-provider
  datasource: 
    url: jdbc:oracle:thin:@192.168.5.146:1521:orcl
    username: "c##learn"  ## 不会转义#号
    password: "c##learn"
    driver-class-name: oracle.jdbc.driver.OracleDriver
    initialSize: 5
    maxActive: 100
    minIdle: 3
    maxWait: 50000
   ## Dubbo 服务提供者配置
  dubbo:
    application:
      name: dubbo-provider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    base-package: com.dubbo.*
    #service: 
    #  interface: ProperticeTestService
     # ref: ProprtticeTestServiceImpl
     # version: 1.0.0
   # annotation:
     # package: com.boot.service.impl
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 10000 #毫秒
    pool:
      max-active: 8 #连接池的最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大连接阻塞等待时间
      max-idle: 8 #连接池中最大空闲连接
      min-idle: 0  #连接池中最小空闲连接
    password: redis   #redis服务连接密码
mybatis:
  type-aliases-package: com.dubbo.base.mapper.*
  mapper-locations: classpath:/com.dubbo.base.mapper/*.xml
  
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    